name: CI

on:
  workflow_dispatch:
    inputs:
      kernel-branch:
        required: true
        type: string
      release-type:
        required: true
        type: choice
        options:
        - kaihatsu
        - seishiki
        default: 'kaihatsu'

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: frstprjkt/kernel_build_action@main
        with:
          kernel-url: https://github.com/frstprjkt/qcom_sm6115
          kernel-branch: ${{ github.event.inputs.kernel-branch }}
          config: vendor/bengal-perf_defconfig vendor/xiaomi/citrus.config
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r563880
          anykernel3: true
          anykernel3-url: https://github.com/frstprjkt/AnyKernel3
          anykernel3-branch: old
          extra-cmd: LLVM=1 LLVM_IAS=1 KBUILD_BUILD_USER=valeryn
          include-dtbo: true
          custom-package-name: valeryn_$(date +%d%H%M)_citrus-${{ github.event.inputs.release-type }}
